[cloudflare]
token = ""

[[cloudflare.zones]]
name = "example.com"  # Zone name or id
records = ["example.com", "*", { type = "AAAA", name = "mail" }]

[bunny]
token = ""

[[bunny.zones]]
name = "example.nl"  # Zone name
records = ["example.nl", "*", { type = "AAAA", name = "mail" }]
